/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DAO_Barang;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Model_Barang;
import service.Service_Barang;
import tablemodel.TableMod_Barang;

/**
 *
 * @author juwita
 */
public class Master_Barang extends javax.swing.JPanel {

    private Service_Barang servis = new DAO_Barang();
    private TableMod_Barang tblModel = new TableMod_Barang();

    /**
     * Creates new form form_barang
     */
    public Master_Barang() {
        initComponents();

        tbl_barang.setModel(tblModel);

        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panel_pencarian = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        t_cari = new javax.swing.JTextField();
        tambahData = new javax.swing.JPanel();
        btn_tambah1 = new javax.swing.JButton();
        btn_batal1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_KodeBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_NamaBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Jenis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmb_Jenis = new javax.swing.JComboBox<>();
        txt_Harga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Stok = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_barang);

        btn_tambah.setBackground(new java.awt.Color(0, 204, 51));
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tambah.setMaximumSize(new java.awt.Dimension(72, 23));
        btn_tambah.setMinimumSize(new java.awt.Dimension(72, 23));
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(255, 0, 0));
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("HAPUS");
        btn_hapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(255, 102, 0));
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("BATAL");
        btn_batal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Data Barang");

        panel_pencarian.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencarian.png"))); // NOI18N

        t_cari.setText("Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel_pencarianLayout = new javax.swing.GroupLayout(panel_pencarian);
        panel_pencarian.setLayout(panel_pencarianLayout);
        panel_pencarianLayout.setHorizontalGroup(
            panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pencarianLayout.createSequentialGroup()
                .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_pencarianLayout.setVerticalGroup(
            panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pencarianLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel9))
            .addComponent(t_cari)
        );

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_hapus)
                        .addComponent(btn_batal))
                    .addComponent(panel_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(tampilData, "card2");

        tambahData.setBackground(new java.awt.Color(255, 255, 255));

        btn_tambah1.setBackground(new java.awt.Color(51, 102, 255));
        btn_tambah1.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah1.setText("TAMBAH");
        btn_tambah1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tambah1.setMaximumSize(new java.awt.Dimension(72, 23));
        btn_tambah1.setMinimumSize(new java.awt.Dimension(72, 23));
        btn_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah1ActionPerformed(evt);
            }
        });

        btn_batal1.setBackground(new java.awt.Color(255, 153, 0));
        btn_batal1.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal1.setText("BATAL");
        btn_batal1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_batal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batal1MouseClicked(evt);
            }
        });
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Tambah Data Barang");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Kode Barang");

        txt_KodeBarang.setEditable(false);
        txt_KodeBarang.setBackground(new java.awt.Color(255, 255, 255));
        txt_KodeBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nama Barang");

        txt_NamaBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Jenis");

        txt_Jenis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Satuan");

        cmb_Jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- satuan -", "Botol ", "Piece", "pack", "Lusin", "Gram", "Mili Liter" }));

        txt_Harga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Harga");

        txt_Stok.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Stok");

        javax.swing.GroupLayout tambahDataLayout = new javax.swing.GroupLayout(tambahData);
        tambahData.setLayout(tambahDataLayout);
        tambahDataLayout.setHorizontalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_KodeBarang)
            .addComponent(txt_NamaBarang)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal1))
                    .addComponent(jLabel2))
                .addContainerGap(272, Short.MAX_VALUE))
            .addComponent(cmb_Jenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txt_Jenis)
            .addComponent(txt_Harga, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(txt_Stok)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tambahDataLayout.setVerticalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahDataLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal1))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_KodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txt_NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(cmb_Jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(tambahData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah1ActionPerformed
        if (btn_tambah1.getText().equals("TAMBAH")) {
            btn_tambah1.setText("SIMPAN");
            txt_KodeBarang.setText(servis.nomor());
        } else if (btn_tambah1.getText().equals("SIMPAN")) {
            simpanData();
        } else if (btn_tambah1.getText().equals("PERBARUI")) {
            perbaruiData();
        }
    }//GEN-LAST:event_btn_tambah1ActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(tampilData);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void tbl_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangMouseClicked
        if (btn_tambah.getText().equals("TAMBAH")) {
            btn_tambah.setText("UBAH");
        }

        btn_hapus.setVisible(true);
        btn_batal.setVisible(true);
    }//GEN-LAST:event_tbl_barangMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        hapusData();
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        loadData();
        tampilPanel();
    }//GEN-LAST:event_btn_batalMouseClicked

    private void btn_batal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batal1MouseClicked
       loadData();
       tampilPanel();
       resetForm();
    }//GEN-LAST:event_btn_batal1MouseClicked

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
         t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
       pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        if (btn_tambah1.getText().equals("TAMBAH")) {
            btn_tambah1.setText("SIMPAN");
            txt_KodeBarang.setText(servis.nomor());
        } else if (btn_tambah1.getText().equals("SIMPAN")) {
            simpanData();
        } else if (btn_tambah1.getText().equals("PERBARUI")) {
            perbaruiData();
        }
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahData);
        mainPanel.repaint();
        mainPanel.revalidate();

        btn_tambah1.setText("SIMPAN");
        txt_KodeBarang.setText(servis.nomor());

        if (btn_tambah.getText().equals("UBAH")) {
            dataTabel();
        }
    }//GEN-LAST:event_btn_tambahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal1;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tambah1;
    private javax.swing.JComboBox<String> cmb_Jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panel_pencarian;
    private javax.swing.JTextField t_cari;
    private javax.swing.JPanel tambahData;
    private javax.swing.JPanel tampilData;
    private javax.swing.JTable tbl_barang;
    private javax.swing.JTextField txt_Harga;
    private javax.swing.JTextField txt_Jenis;
    private javax.swing.JTextField txt_KodeBarang;
    private javax.swing.JTextField txt_NamaBarang;
    private javax.swing.JTextField txt_Stok;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
        List<Model_Barang> list = servis.getData();
        tblModel.setData(list);
    }

    private void tampilData() {
        List<Model_Barang> list = servis.getData();
        mainPanel.removeAll();
        mainPanel.add(tampilData);
        mainPanel.revalidate();
        mainPanel.repaint();

    }

    private void resetForm() {
        btn_tambah.requestFocus();
        btn_tambah.setText("TAMBAH");
        txt_KodeBarang.setText("");
        txt_NamaBarang.setText("");
        txt_Harga.setText("");
        txt_Stok.setText("");
        cmb_Jenis.setSelectedIndex(0);
        txt_Jenis.setText("");
    }

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Master_Barang()); 
        mainPanel.repaint();
        mainPanel.revalidate();        
    }

    private void dataTabel() {
        tampilData.setVisible(false);
        tambahData.setVisible(true);

        int row = tbl_barang.getSelectedRow();
        jLabel2.setText("Perbarui Data Barang");

        txt_KodeBarang.setEnabled(false);

        txt_KodeBarang.setText(tbl_barang.getModel().getValueAt(row, 1).toString());
        txt_NamaBarang.setText(tbl_barang.getModel().getValueAt(row, 2).toString());
        cmb_Jenis.setSelectedItem(tbl_barang.getModel().getValueAt(row, 3).toString());
        txt_Jenis.setText(tbl_barang.getModel().getValueAt(row, 6).toString());
        txt_Harga.setText(tbl_barang.getModel().getValueAt(row, 4).toString());
        txt_Stok.setText(tbl_barang.getModel().getValueAt(row, 5).toString());

        aktif();
        btn_tambah1.setText("PERBARUI");
        btn_batal.setVisible(true);

    }

    private void aktif() {
        txt_NamaBarang.setEnabled(true);
        cmb_Jenis.setEnabled(true);
        txt_Harga.setEnabled(true);
        txt_Stok.setEnabled(true);
        txt_Jenis.setEnabled(true);
    }

    private boolean validasiInput() {
        boolean valid = true;
        if (txt_KodeBarang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Barang tidak boleh kosong");
            valid = false;
        } else if (txt_NamaBarang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Barang tidak boleh kosong");
            valid = false;
        } else if (cmb_Jenis.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Satuan tidak boleh kosong");
            valid = false;
        } else if (txt_Harga.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harga tidak boleh kosong");
            valid = false;
        } else if (txt_Stok.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Stok tidak boleh kosong");
            valid = false;
        } else if (txt_Jenis.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Jenis tidak boleh kosong");
            valid = false;
        } else {
            valid = true; // Pastikan ini ditambahkan!
        }
        return valid;
    }

    private void simpanData() {
        if (validasiInput() == true) {
            DAO_Barang dao = new DAO_Barang();
            String kodeBarang = txt_KodeBarang.getText();
            String namaBarang = txt_NamaBarang.getText();
            String jenisBarang = txt_Jenis.getText();
            String satuan = cmb_Jenis.getSelectedItem().toString();
            Long harga = Long.parseLong(txt_Harga.getText());
            int stok = Integer.parseInt(txt_Stok.getText());

            Model_Barang brg = new Model_Barang();

            brg.setKode_barang(kodeBarang);
            brg.setNama_barang(namaBarang);
            brg.setJenis_barang(jenisBarang);
            brg.setSatuan(satuan);
            brg.setHarga(harga);
            brg.setStok(stok);

            servis.tambahData(brg);
            tblModel.tambahData(brg);

            loadData();
            resetForm();
            tampilPanel();
            btn_tambah1.setText("TAMBAH");

        }
    }

    private void perbaruiData() {
        int index = tbl_barang.getSelectedRow();
        if (index != -1) {
            Model_Barang mobar = tblModel.getData(tbl_barang.convertRowIndexToModel(index));

            if (validasiInput() == true) {
                // Ambil data dari form
                String kodeBarang = txt_KodeBarang.getText();
                String namaBarang = txt_NamaBarang.getText();
                String jenisBarang = txt_Jenis.getText();
                String satuan = cmb_Jenis.getSelectedItem().toString();
                Long harga = Long.parseLong(txt_Harga.getText());
                int stok = Integer.parseInt(txt_Stok.getText());

                // Buat objek barang baru
                Model_Barang brg = new Model_Barang();
                brg.setKode_barang(kodeBarang);
                brg.setNama_barang(namaBarang);
                brg.setJenis_barang(jenisBarang);
                brg.setSatuan(satuan);
                brg.setHarga(harga);
                brg.setStok(stok);

                // Debug log
                System.out.println("Memperbarui data: " + brg.getKode_barang());

                // Update data di layanan dan tabel
                servis.perbaruiData(brg); // DAO
                tblModel.perbaruiData(index, brg); // Model GUI

                // Refresh tabel dan reset form
                loadData();
                resetForm();
                tampilPanel();
            }
        }
    }

    private void hapusData() {
        int index = tbl_barang.getSelectedRow();
        if (index != -1) {
            Model_Barang brg = tblModel.getData(tbl_barang.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
            {
                servis.hapusData(brg);
                tblModel.hapusData(index);
                loadData();
                resetForm();
            }else{
                JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan dihapus");
            }
        }
    }

    private void pencarian() {
         List<Model_Barang> list = servis.pencarian(t_cari.getText());
         tblModel.setData(list);
    }

}
