/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DAO_Pengguna;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Model_Pengguna;
import service.Service_Pengguna;
import tablemodel.TableMod_Pengguna;

/**
 *
 * @author juwita
 */
public class Master_Pengguna extends javax.swing.JPanel {

    private Service_Pengguna servis = new DAO_Pengguna();
    private TableMod_Pengguna tblModel = new TableMod_Pengguna();

    /**
     * Creates new form form_barang
     */
    public Master_Pengguna() {
        initComponents();

        tbl_pengguna.setModel(tblModel);

        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pengguna = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panel_pencarian = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        t_cari = new javax.swing.JTextField();
        tambahData = new javax.swing.JPanel();
        btn_tambah1 = new javax.swing.JButton();
        btn_batal1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_Id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_Nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_Username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_Alamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_telepon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbx_level = new javax.swing.JComboBox<>();
        t_Password = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        tbl_pengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_penggunaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pengguna);

        btn_tambah.setBackground(new java.awt.Color(0, 204, 51));
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tambah.setMaximumSize(new java.awt.Dimension(72, 23));
        btn_tambah.setMinimumSize(new java.awt.Dimension(72, 23));
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(255, 0, 0));
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("HAPUS");
        btn_hapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(255, 102, 0));
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("BATAL");
        btn_batal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Data Pengguna");

        panel_pencarian.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencarian.png"))); // NOI18N

        t_cari.setText("Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel_pencarianLayout = new javax.swing.GroupLayout(panel_pencarian);
        panel_pencarian.setLayout(panel_pencarianLayout);
        panel_pencarianLayout.setHorizontalGroup(
            panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pencarianLayout.createSequentialGroup()
                .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_pencarianLayout.setVerticalGroup(
            panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pencarianLayout.createSequentialGroup()
                .addGroup(panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pencarianLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(t_cari))
                .addContainerGap())
        );

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_batal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_hapus)
                            .addComponent(btn_batal))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
                    .addComponent(panel_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainPanel.add(tampilData, "card2");

        tambahData.setBackground(new java.awt.Color(255, 255, 255));

        btn_tambah1.setBackground(new java.awt.Color(51, 102, 255));
        btn_tambah1.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah1.setText("TAMBAH");
        btn_tambah1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tambah1.setMaximumSize(new java.awt.Dimension(72, 23));
        btn_tambah1.setMinimumSize(new java.awt.Dimension(72, 23));
        btn_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah1ActionPerformed(evt);
            }
        });

        btn_batal1.setBackground(new java.awt.Color(255, 153, 0));
        btn_batal1.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal1.setText("BATAL");
        btn_batal1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_batal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batal1MouseClicked(evt);
            }
        });
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Tambah Data Pengguna");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ID ");

        t_Id.setEditable(false);
        t_Id.setBackground(new java.awt.Color(255, 255, 255));
        t_Id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nama ");

        t_Nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Username");

        t_Username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Password");

        t_Alamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Telepon");

        t_telepon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Alamat");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Level");

        cbx_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Akses Level -", "Owner", "Staff", " " }));

        t_Password.setText("jPasswordField1");
        t_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_PasswordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout tambahDataLayout = new javax.swing.GroupLayout(tambahData);
        tambahData.setLayout(tambahDataLayout);
        tambahDataLayout.setHorizontalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t_Id)
            .addComponent(t_Nama)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal1))
                    .addComponent(jLabel2))
                .addContainerGap(217, Short.MAX_VALUE))
            .addComponent(t_Username)
            .addComponent(t_Alamat, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(t_telepon)
            .addComponent(cbx_level, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(t_Password)
        );
        tambahDataLayout.setVerticalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahDataLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal1))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(t_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(t_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        mainPanel.add(tambahData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahData);
        mainPanel.repaint();
        mainPanel.revalidate();

        btn_tambah1.setText("SIMPAN");
        t_Id.setText(servis.nomor());
        t_Id.setEnabled(false);
        

        if (btn_tambah.getText().equals("UBAH")) {
            dataTabel();
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah1ActionPerformed
        if (btn_tambah1.getText().equals("TAMBAH")) {
            btn_tambah1.setText("SIMPAN");
            t_Id.setText(servis.nomor());
        } else if (btn_tambah1.getText().equals("SIMPAN")) {
            simpanData();
        } else if (btn_tambah1.getText().equals("PERBARUI")) {
            perbaruiData();
        }
    }//GEN-LAST:event_btn_tambah1ActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(tampilData);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void tbl_penggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_penggunaMouseClicked
        if (btn_tambah.getText().equals("TAMBAH")) {
            btn_tambah.setText("UBAH");
        }

        btn_hapus.setVisible(true);
        btn_batal.setVisible(true);
    }//GEN-LAST:event_tbl_penggunaMouseClicked

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed

    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        hapusData();
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        loadData();
        tampilPanel();
    }//GEN-LAST:event_btn_batalMouseClicked

    private void btn_batal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batal1MouseClicked
        loadData();
        tampilPanel();
        resetForm();
    }//GEN-LAST:event_btn_batal1MouseClicked

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void t_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_PasswordFocusGained
       String username=t_Password.getText();
        if(username.equals("password")){
            t_Password.setText("");
        }
    }//GEN-LAST:event_t_PasswordFocusGained

    private void t_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_PasswordFocusLost
        String username = t_Password.getText();
        if (username.equals("") || username.equals("pasword")) {
        t_Password.setText("password");
       }
    }//GEN-LAST:event_t_PasswordFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal1;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tambah1;
    private javax.swing.JComboBox<String> cbx_level;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panel_pencarian;
    private javax.swing.JTextField t_Alamat;
    private javax.swing.JTextField t_Id;
    private javax.swing.JTextField t_Nama;
    private javax.swing.JPasswordField t_Password;
    private javax.swing.JTextField t_Username;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_telepon;
    private javax.swing.JPanel tambahData;
    private javax.swing.JPanel tampilData;
    private javax.swing.JTable tbl_pengguna;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
        List<Model_Pengguna> list = servis.getData();
        tblModel.setData(list);
    }

    private void tampilData() {
        List<Model_Pengguna> list = servis.getData();
        mainPanel.removeAll();
        mainPanel.add(tampilData);
        mainPanel.revalidate();
        mainPanel.repaint();

    }

    private void resetForm() {
        btn_tambah.requestFocus();
        btn_tambah.setText("TAMBAH");
        t_Id.setText("");
        t_Nama.setText("");
        t_Password.setText("");
        t_Username.setText("");
    }

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Master_Pengguna());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void dataTabel() {
        tampilData.setVisible(false);
        tambahData.setVisible(true);

        int row = tbl_pengguna.getSelectedRow();
        jLabel1.setText("Perbarui Data Pengguna");
        
        t_Id.setEnabled(false);
        t_Nama.setEnabled(true);

        t_Id.setText(tbl_pengguna.getModel().getValueAt(row, 0).toString());
        t_Nama.setText(tbl_pengguna.getModel().getValueAt(row, 1).toString());
        t_Username.setText(tbl_pengguna.getModel().getValueAt(row, 2).toString());
        t_Password.setText(tbl_pengguna.getModel().getValueAt(row, 3).toString());        
        t_telepon.setText(tbl_pengguna.getModel().getValueAt(row, 4).toString());
        t_Alamat.setText(tbl_pengguna.getModel().getValueAt(row, 5).toString());
        cbx_level.setSelectedItem(tbl_pengguna.getModel().getValueAt(row, 6).toString());

        aktif();
        btn_tambah1.setText("PERBARUI");
        btn_batal.setVisible(true);
        
    }

    private void aktif() {
        t_Password.setEnabled(true);
        t_Id.setEnabled(false);
        t_Username.setEnabled(true);
        t_telepon.setVisible(true);
        t_Alamat.setVisible(true);

    }

    private boolean validasiInput() {
        boolean valid = true;
        if (t_Id.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Id tidak boleh kosong");
            valid = false;
        } else if (t_Nama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong");
            valid = false;
        } else if (t_Password.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong");
            valid = false;
        } else if (t_Username.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong");
            valid = false;
        } else if (t_telepon.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Telepon tidak boleh kosong");
            valid = false;
        } else if (t_Alamat.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Alamat tidak boleh kosong");
            valid = false;
        } else if (cbx_level.getSelectedItem().equals("- Pilih Akses Level -")) {
            JOptionPane.showMessageDialog(null, "Pilih Level ");
            valid = false;
        } else {
            valid = true;
        }
        return valid;
    }

    private void simpanData() {
        // Validasi input sebelum menyimpan data
        if (validasiInput() == true) {
            DAO_Pengguna dao = new DAO_Pengguna();
            String idPengguna = t_Id.getText();
            String nama = t_Nama.getText();
            String username = t_Username.getText();
            String password = t_Password.getText();
            String telp = t_telepon.getText();
            String alamat = t_Alamat.getText();
            String level = cbx_level.getSelectedItem().toString();

            // Buat objek Model_Pengguna baru dan set data
            Model_Pengguna pengguna = new Model_Pengguna();
            pengguna.setId_pengguna(idPengguna);
            pengguna.setNama_pengguna(nama);
            pengguna.setUsername(username);
            pengguna.setPassword(password);
            pengguna.setTelp_pengguna(telp);
            pengguna.setAlamat_pengguna(alamat);
            pengguna.setLevel(level);

            servis.tambahData(pengguna);
            tblModel.tambahData(pengguna);
            loadData();
            resetForm();
            tampilPanel();
            btn_tambah1.setText("TAMBAH");
        }
    }

    private void perbaruiData() {
        int index = tbl_pengguna.getSelectedRow();  // Mendapatkan index baris yang dipilih
        if (index != -1) {  // Jika ada baris yang dipilih

            Model_Pengguna mod_pen = tblModel.getData(tbl_pengguna.convertRowIndexToModel(index));

            // Validasi input
            if (validasiInput() == true) {

                String idPengguna = t_Id.getText();
                String nama = t_Nama.getText();
                String username = t_Username.getText();
                String password = t_Password.getText();
                String telp = t_telepon.getText();
                String alamat = t_Alamat.getText();
                String level = cbx_level.getSelectedItem().toString();

                // Buat objek Model_Pengguna baru dan set data
                Model_Pengguna model = new Model_Pengguna();
                model.setId_pengguna(idPengguna);
                model.setNama_pengguna(nama);
                model.setUsername(username);
                model.setPassword(password);
                model.setTelp_pengguna(telp);
                model.setAlamat_pengguna(alamat);
                model.setLevel(level);

                servis.perbaruiData(model);

                // Update data di tabel model GUI
                tblModel.perbaruiData(index, model);

                // Refresh tabel dan reset form
                loadData();
                resetForm();
                tampilPanel();
            }
        }
    }

    private void hapusData() {
        int index = tbl_pengguna.getSelectedRow();
        if (index != -1) {
            Model_Pengguna distributor = tblModel.getData(tbl_pengguna.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                servis.hapusData(distributor);
                tblModel.hapusData(index);
                loadData();
                resetForm();
            } else {
                JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan dihapus");
            }
        }
    }

    private void pencarian() {
        List<Model_Pengguna> list = servis.pencarian(t_cari.getText());
        tblModel.setData(list);

    }

}
