/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DAO_Barang;
import dao.DAO_BarangMasuk;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Model_Barang;
import model.Model_Barangmasuk;
import model.Model_Pengguna;
import service.Service_Barang;
import service.Service_Barangmasuk;
import tablemodel.TableMod_Barang;
import tablemodel.TableMod_Barangmasuk;

/**
 *
 * @author juwita
 */
public class Transaksi_Barangmasuk extends javax.swing.JPanel {

    private Service_Barangmasuk servis_psn = new DAO_BarangMasuk();
    private Service_Barang servis_det = new DAO_Barang();

    private TableMod_Barangmasuk tblModel_psn = new TableMod_Barangmasuk();
    private TableMod_Barang tblModel_det = new TableMod_Barang();

    //private final int noColumnIndex = 0;
    // private final int noColumnWidth = 50;
    /**
     * Creates new form form_barang
     */
    public Transaksi_Barangmasuk() {
        initComponents();

        tbl_pesanan.setModel(tblModel_psn);

        //setColumnWidth();
        loadData();

    }

    /*private void setColumnWidth() {
        TableColumnModel columnModel = tbl_pesanan.getColumnModel();
         columnModel.getColumn(noColumnIndex).setPreferredWidth(noColumnWidth);
        columnModel.getColumn(noColumnIndex).setMaxWidth(noColumnWidth);
        columnModel.getColumn(noColumnIndex).setMinWidth(noColumnWidth);
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pesanan = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        panel_pencarian = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        t_cari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tambahData = new javax.swing.JPanel();
        btn_tambah1 = new javax.swing.JButton();
        btn_batal1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_tanggalMasuk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_kodeBarangMasuk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ID_Pengguna = new javax.swing.JLabel();
        t_namaBarangMasuk = new javax.swing.JTextField();
        ID_Pengguna1 = new javax.swing.JLabel();
        btn_barangmasuk = new javax.swing.JButton();
        t_jumlah = new javax.swing.JTextField();
        t_satuan = new javax.swing.JTextField();
        t_jenis = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        tbl_pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pesanan);

        btn_tambah.setBackground(new java.awt.Color(0, 204, 51));
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tambah.setMaximumSize(new java.awt.Dimension(72, 23));
        btn_tambah.setMinimumSize(new java.awt.Dimension(72, 23));
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(255, 0, 0));
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("HAPUS");
        btn_hapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(255, 102, 0));
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("BATAL");
        btn_batal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });

        panel_pencarian.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencarian.png"))); // NOI18N

        t_cari.setText("Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel_pencarianLayout = new javax.swing.GroupLayout(panel_pencarian);
        panel_pencarian.setLayout(panel_pencarianLayout);
        panel_pencarianLayout.setHorizontalGroup(
            panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pencarianLayout.createSequentialGroup()
                .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_pencarianLayout.setVerticalGroup(
            panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pencarianLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel9))
            .addComponent(t_cari)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data Barang Masuk");

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_batal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(panel_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_hapus)
                        .addComponent(btn_batal))
                    .addComponent(panel_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(250, 250, 250))
        );

        mainPanel.add(tampilData, "card2");

        tambahData.setBackground(new java.awt.Color(255, 255, 255));

        btn_tambah1.setBackground(new java.awt.Color(51, 102, 255));
        btn_tambah1.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah1.setText("TAMBAH");
        btn_tambah1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tambah1.setMaximumSize(new java.awt.Dimension(72, 23));
        btn_tambah1.setMinimumSize(new java.awt.Dimension(72, 23));
        btn_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah1ActionPerformed(evt);
            }
        });

        btn_batal1.setBackground(new java.awt.Color(255, 153, 0));
        btn_batal1.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal1.setText("BATAL");
        btn_batal1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_batal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batal1MouseClicked(evt);
            }
        });
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Tambah Data Barang Masuk");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tanggal Masuk");

        t_tanggalMasuk.setEditable(false);
        t_tanggalMasuk.setBackground(new java.awt.Color(255, 255, 255));
        t_tanggalMasuk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Kode Barang Masuk");

        t_kodeBarangMasuk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Satuan");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Nama Barang");

        ID_Pengguna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ID_Pengguna.setText("Jumlah");

        t_namaBarangMasuk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        ID_Pengguna1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ID_Pengguna1.setText("Jenis");

        btn_barangmasuk.setText("PILIH");
        btn_barangmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_barangmasukActionPerformed(evt);
            }
        });

        t_jumlah.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        t_satuan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        t_jenis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout tambahDataLayout = new javax.swing.GroupLayout(tambahData);
        tambahData.setLayout(tambahDataLayout);
        tambahDataLayout.setHorizontalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t_tanggalMasuk)
            .addComponent(t_kodeBarangMasuk)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal1))
                    .addComponent(jLabel2))
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(ID_Pengguna)
                    .addComponent(ID_Pengguna1)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(t_namaBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(btn_barangmasuk)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(t_satuan)
            .addComponent(t_jumlah)
            .addComponent(t_jenis)
        );
        tambahDataLayout.setVerticalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahDataLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal1))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_tanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(t_kodeBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(17, 17, 17)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_namaBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_barangmasuk))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ID_Pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(ID_Pengguna1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        mainPanel.add(tambahData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahData);
        mainPanel.repaint();
        mainPanel.revalidate();

        btn_tambah1.setText("SIMPAN");
        t_kodeBarangMasuk.setText(servis_psn.nomor());
        t_kodeBarangMasuk.setEnabled(false);

        java.time.LocalDate today = java.time.LocalDate.now();
        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd");
        t_tanggalMasuk.setText(today.format(formatter));
        t_tanggalMasuk.setEnabled(false);

        if (btn_tambah.getText().equals("UBAH")) {
            dataTabel();
            aktif();
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void tbl_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pesananMouseClicked
          if (btn_tambah.getText().equals("TAMBAH")) {
            btn_tambah.setText("UBAH");
        }

        btn_hapus.setVisible(true);
        btn_batal.setVisible(true);
    }//GEN-LAST:event_tbl_pesananMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        hapusData();
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        loadData();
        tampilPanel();
    }//GEN-LAST:event_btn_batalMouseClicked

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(tampilData);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void btn_batal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batal1MouseClicked
        loadData();
        tampilPanel();
        resetForm();
    }//GEN-LAST:event_btn_batal1MouseClicked

    private void btn_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah1ActionPerformed
        if (btn_tambah1.getText().equals("TAMBAH")) {
            btn_tambah1.setText("SIMPAN");
            t_tanggalMasuk.setText(servis_psn.nomor());
        } else if (btn_tambah1.getText().equals("SIMPAN")) {
            simpanData();
        } else if (btn_tambah1.getText().equals("PERBARUI")) {
            perbaruiData();
        }
    }//GEN-LAST:event_btn_tambah1ActionPerformed

    private void btn_barangmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_barangmasukActionPerformed
        boolean closable = true;

        Data_BarangMasuk datmas = new Data_BarangMasuk(null, closable);
        datmas.setVisible(true);

        t_namaBarangMasuk.setText(datmas.model.getNama_barang());
        t_satuan.setText(datmas.model.getSatuan());
        t_jenis.setText(datmas.model.getJenis_barang());

        btn_barangmasuk.requestFocus();
        t_namaBarangMasuk.setEnabled(false);
        t_satuan.setEnabled(false);
        t_jenis.setEnabled(false);


    }//GEN-LAST:event_btn_barangmasukActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID_Pengguna;
    private javax.swing.JLabel ID_Pengguna1;
    private javax.swing.JButton btn_barangmasuk;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal1;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tambah1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panel_pencarian;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_jenis;
    private javax.swing.JTextField t_jumlah;
    private javax.swing.JTextField t_kodeBarangMasuk;
    private javax.swing.JTextField t_namaBarangMasuk;
    private javax.swing.JTextField t_satuan;
    private javax.swing.JTextField t_tanggalMasuk;
    private javax.swing.JPanel tambahData;
    private javax.swing.JPanel tampilData;
    private javax.swing.JTable tbl_pesanan;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
        List<Model_Barangmasuk> list = servis_psn.getData();
        tblModel_psn.setData(list);
    }

    private void tampilData() {
        List<Model_Barangmasuk> list = servis_psn.getData();
        mainPanel.removeAll();
        mainPanel.add(tampilData);
        mainPanel.revalidate();
        mainPanel.repaint();

    }

    private void resetForm() {
        btn_tambah.requestFocus();
        btn_tambah.setText("TAMBAH");
        t_tanggalMasuk.setText("");
        t_kodeBarangMasuk.setText("");
        t_namaBarangMasuk.setText("");
        t_satuan.setText("");
        t_jumlah.setText("");
        t_jenis.setText("");

    }

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Transaksi_Barangmasuk());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    
private void dataTabel() {
    tampilData.setVisible(false);
    tambahData.setVisible(true);

    int row = tbl_pesanan.getSelectedRow();
    jLabel2.setText("Perbarui Data Barang Masuk");

    t_tanggalMasuk.setEnabled(false);

    // Set nilai dari tabel ke input form
    t_tanggalMasuk.setText(tbl_pesanan.getModel().getValueAt(row, 1).toString());
    t_kodeBarangMasuk.setText(tbl_pesanan.getModel().getValueAt(row, 2).toString());
    t_namaBarangMasuk.setText(tbl_pesanan.getModel().getValueAt(row, 3).toString());
    t_satuan.setText(tbl_pesanan.getModel().getValueAt(row, 4).toString());
    t_jumlah.setText(tbl_pesanan.getModel().getValueAt(row, 5).toString());
    t_jenis.setText(tbl_pesanan.getModel().getValueAt(row, 6).toString());

    

    aktif();
    btn_tambah1.setText("PERBARUI");
    btn_batal.setVisible(true);
    t_namaBarangMasuk.setEnabled(false);
    t_satuan.setEnabled(false);
    t_jenis.setEnabled(false);
}
 
    private void aktif() {
    t_kodeBarangMasuk.setEnabled(false);
    t_jumlah.setEnabled(true);
   
    btn_tambah1.setEnabled(true);
    btn_batal.setEnabled(true);
}
    private boolean validasiInput() {
        boolean valid = true;
        if (t_tanggalMasuk.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "tanggal tidak boleh kosong");
            valid = false;
        } else if (t_kodeBarangMasuk.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode barang masuk tidak boleh kosong");
            valid = false;
        } else if (t_namaBarangMasuk.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih Barang Masuk");
            valid = false;
        } else if (t_jumlah.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Jumlah Barang tidak boleh kosong");
            valid = false;
        } else {
            valid = true; // Pastikan valid true jika semua validasi terpenuhi
        }
        return valid;
    }

    private void simpanData() {
        if (validasiInput() == true) {
            try {
                String tgl = t_tanggalMasuk.getText();
                String kodmas = t_kodeBarangMasuk.getText();
                String nambar = t_namaBarangMasuk.getText();
                String satuan = t_satuan.getText();
                int jml = Integer.parseInt(t_jumlah.getText());
                String jenis = t_jenis.getText();

                // Buat objek Model_Barang
                Model_Barang barang = new Model_Barang();
                barang.setNama_barang(nambar);
                barang.setJenis_barang(jenis);
                barang.setSatuan(satuan);

                // Buat objek Model_Barangmasuk dan hubungkan Model_Barang dengan Model_Barangmasuk
                Model_Barangmasuk model = new Model_Barangmasuk();
                model.setTgl_masuk(tgl);
                model.setJumlah_masuk(jml);
                model.setKode_barangmasuk(kodmas);
                model.setMod_bar(barang);  // Pastikan properti mod_bar sudah diisi!

                // Simpan data ke layanan DAO dan tabel
                servis_psn.tambahData(model);
                tblModel_psn.tambahData(model);

                loadData();
                resetForm();
                tampilPanel();
                btn_tambah1.setText("TAMBAH");

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Input jumlah harus berupa angka.");
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(this, "Pastikan semua input diisi dengan benar.");
            }
        }
    }

    
    private void perbaruiData() {
    int index = tbl_pesanan.getSelectedRow();
    if (index != -1) {
        Model_Barangmasuk mod = tblModel_psn.getData(tbl_pesanan.convertRowIndexToModel(index));

                String tgl = t_tanggalMasuk.getText();
                String kodmas = t_kodeBarangMasuk.getText();
                String nambar = t_namaBarangMasuk.getText();
                String satuan = t_satuan.getText();
                int jml = Integer.parseInt(t_jumlah.getText());
                String jenis = t_jenis.getText();

                // Buat objek Model_Barang
                Model_Barang barang = new Model_Barang();
                barang.setNama_barang(nambar);
                barang.setJenis_barang(jenis);
                barang.setSatuan(satuan);

                Model_Barangmasuk mod_masuk = new Model_Barangmasuk();
                mod_masuk.setTgl_masuk(tgl);
                mod_masuk.setJumlah_masuk(jml);
                mod_masuk.setKode_barangmasuk(kodmas);
                
                mod_masuk.setMod_bar(barang); 
            // Debug log
            System.out.println("Memperbarui data: " + mod.getKode_barangmasuk());

            // Update data di layanan dan tabel
            servis_psn.perbaruiData(mod_masuk); // DAO
            tblModel_psn.perbaruiData(index, mod); // Model GUI

            // Refresh tabel dan reset form
            loadData();
            resetForm();
            tampilPanel();
    }
}
    private void hapusData() {
        int index = tbl_pesanan.getSelectedRow();
        if (index != -1) {
            Model_Barangmasuk brgmasuk = tblModel_psn.getData(tbl_pesanan.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                servis_psn.hapusData(brgmasuk);
                tblModel_psn.hapusData(index);
                loadData();
                resetForm();
            } else {
                JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan dihapus");
            }
        }
    }

    private void pencarian() {
        List<Model_Barangmasuk> list = servis_psn.pencarian(t_cari.getText());
        tblModel_psn.setData(list);
    }


}
