/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DAO_DetPemesanan;
import dao.DAO_Pemesanan;
import dao.DAO_SemPemesanan;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Model_Barang;
import model.Model_DetPemesanan;
import model.Model_Distributor;
import model.Model_Pemesanan;
import model.Model_Pengguna;
import model.Model_SemPemesanan;
import service.Service_DetPemesanan;
import service.Service_Pemesanan;
import service.Service_SemPemesanan;
import tablemodel.TableMod_DetPemesanan;
import tablemodel.TableMod_Pemesanan;
import tablemodel.TableMod_SemPemesanan;

import java.text.*;
import java.awt.print.*;
import javax.swing.JTable;

/**
 *
 * @author juwita
 */
public class Transaksi_Pemesanan extends javax.swing.JPanel {

    private Service_Pemesanan servis_psn = new DAO_Pemesanan();
    private Service_DetPemesanan servis_det = new DAO_DetPemesanan();
    private Service_SemPemesanan servis_sem = new DAO_SemPemesanan();

    private TableMod_Pemesanan tblModel_psn = new TableMod_Pemesanan();
    private TableMod_DetPemesanan tblModel_det = new TableMod_DetPemesanan();
    private TableMod_SemPemesanan tblModel_sem = new TableMod_SemPemesanan();

    //private final int noColumnIndex = 0;
    // private final int noColumnWidth = 50;
    /**
     * Creates new form form_barang
     */
    public Transaksi_Pemesanan() {
        initComponents();

        tbl_sementara.setModel(tblModel_psn);

        tbl_sementara.setModel(tblModel_sem);
        //setColumnWidth();

        loadDataSementara();

    }

    /*private void setColumnWidth() {
        TableColumnModel columnModel = tbl_pesanan.getColumnModel();
         columnModel.getColumn(noColumnIndex).setPreferredWidth(noColumnWidth);
        columnModel.getColumn(noColumnIndex).setMaxWidth(noColumnWidth);
        columnModel.getColumn(noColumnIndex).setMinWidth(noColumnWidth);
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tambahData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        t_namaDistributor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_idDistributor = new javax.swing.JTextField();
        btn_distributor = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        t_namaBarang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        t_kodeBarang = new javax.swing.JTextField();
        btn_barang = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lb_satuan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        t_satuan = new javax.swing.JTextField();
        t_subtotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        t_harga = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btn_tambahSementara = new javax.swing.JButton();
        txt_jumlah = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_sementara = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lb_total = new javax.swing.JLabel();
        btn_batal = new javax.swing.JButton();
        btn_perbarui4 = new javax.swing.JButton();
        btn_hapus4 = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        tambahData.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Tambah Pemesanan");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Nama Distributor");

        t_namaDistributor.setEditable(false);
        t_namaDistributor.setBackground(new java.awt.Color(255, 255, 255));
        t_namaDistributor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("ID Distributor");

        t_idDistributor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        btn_distributor.setText("jToggleButton1");
        btn_distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_distributorActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Distributor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(t_idDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(t_namaDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(114, 114, 114)
                        .addComponent(jLabel7)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_idDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_distributor)
                    .addComponent(t_namaDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Nama Barang");

        t_namaBarang.setEditable(false);
        t_namaBarang.setBackground(new java.awt.Color(255, 255, 255));
        t_namaBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Kode Barang");

        t_kodeBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        btn_barang.setText("jToggleButton1");
        btn_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_barangActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(51, 51, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Barang");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel6)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lb_satuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_satuan.setText("Satuan");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Harga");

        t_satuan.setEditable(false);
        t_satuan.setBackground(new java.awt.Color(255, 255, 255));
        t_satuan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        t_subtotal.setEditable(false);
        t_subtotal.setBackground(new java.awt.Color(255, 255, 255));
        t_subtotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Jumlah");

        t_harga.setEditable(false);
        t_harga.setBackground(new java.awt.Color(255, 255, 255));
        t_harga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Sub Total");

        btn_tambahSementara.setBackground(new java.awt.Color(51, 204, 0));
        btn_tambahSementara.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_tambahSementara.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambahSementara.setText("TAMBAH BARANG");
        btn_tambahSementara.setActionCommand("");
        btn_tambahSementara.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tambahSementara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahSementaraActionPerformed(evt);
            }
        });

        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(t_kodeBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t_namaBarang)
                    .addComponent(t_satuan)
                    .addComponent(t_subtotal)
                    .addComponent(t_harga, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_tambahSementara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(lb_satuan)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_jumlah))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_barang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_satuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(2, 2, 2)
                .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_tambahSementara)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tbl_sementara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_sementara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sementaraMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_sementara);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Total Pesan");

        lb_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_total.setText("Total Pesan");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(151, 151, 151)
                .addComponent(lb_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lb_total))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btn_batal.setBackground(new java.awt.Color(0, 51, 153));
        btn_batal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("BATAL");
        btn_batal.setActionCommand("");
        btn_batal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_perbarui4.setBackground(new java.awt.Color(0, 51, 153));
        btn_perbarui4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_perbarui4.setForeground(new java.awt.Color(255, 255, 255));
        btn_perbarui4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_perbarui4.setLabel("PERBARUI");
        btn_perbarui4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perbarui4ActionPerformed(evt);
            }
        });

        btn_hapus4.setBackground(new java.awt.Color(0, 51, 153));
        btn_hapus4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_hapus4.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus4.setText("HAPUS");
        btn_hapus4.setActionCommand("");
        btn_hapus4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_hapus4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus4ActionPerformed(evt);
            }
        });

        btn_cetak.setBackground(new java.awt.Color(0, 51, 153));
        btn_cetak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cetak.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetak.setText("CETAK");
        btn_cetak.setActionCommand("");
        btn_cetak.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahDataLayout = new javax.swing.GroupLayout(tambahData);
        tambahData.setLayout(tambahDataLayout);
        tambahDataLayout.setHorizontalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                            .addGroup(tambahDataLayout.createSequentialGroup()
                                .addComponent(btn_perbarui4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_hapus4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addComponent(btn_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        tambahDataLayout.setVerticalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahDataLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cetak))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_perbarui4)
                    .addComponent(btn_batal)
                    .addComponent(btn_hapus4))
                .addGap(106, 106, 106))
        );

        mainPanel.add(tambahData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_distributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_distributorActionPerformed
        boolean closable = true;

        Data_Distributor datdis = new Data_Distributor(null, closable);
        datdis.setVisible(true);

        t_idDistributor.setText(datdis.dst.getId_distributor());
        t_namaDistributor.setText(datdis.dst.getNama_distributor());

        btn_barang.requestFocus();
        t_idDistributor.setEnabled(false);
        t_namaDistributor.setEnabled(false);

    }//GEN-LAST:event_btn_distributorActionPerformed

    private void btn_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_barangActionPerformed
        boolean closable = true;

        Data_Barang model_bar = new Data_Barang(null, closable);
        model_bar.setVisible(true);

        t_kodeBarang.setText(model_bar.model.getKode_barang());
        t_namaBarang.setText(model_bar.model.getNama_barang());
        t_satuan.setText(model_bar.model.getSatuan());
        t_harga.setText(model_bar.model.getHarga().toString());

        btn_barang.requestFocus();
        t_kodeBarang.setEnabled(false);
        t_namaBarang.setEnabled(false);
        t_satuan.setEnabled(false);
        t_harga.setEnabled(false);

    }//GEN-LAST:event_btn_barangActionPerformed

    private void btn_tambahSementaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahSementaraActionPerformed
        try {
            // Mengambil input dari user
            String kode = t_kodeBarang.getText();
            String nama = t_namaBarang.getText();
            String satuan = t_satuan.getText();
            Long harga = Long.parseLong(t_harga.getText());
            Long jumlah = Long.parseLong(txt_jumlah.getText());
            Long subtotal = harga * jumlah; // Kalkulasi subtotal otomatis
            String status = "Sedang di pesan";

            // Membuat model data
            Model_Barang brg = new Model_Barang();
            Model_DetPemesanan det_psn = new Model_DetPemesanan();
            Model_SemPemesanan smt = new Model_SemPemesanan();

            brg.setKode_barang(kode);
            brg.setNama_barang(nama);
            brg.setHarga(harga);
            brg.setSatuan(satuan);

            det_psn.setJml_pesan(jumlah);
            det_psn.setSubtotal_pesan(subtotal);
            det_psn.setStatus(status);

            smt.setMod_barang(brg);
            smt.setMod_detpesan(det_psn);

            // Menambahkan data ke database sementara dan menghitung total
            servis_sem.tambahData(smt);
            servis_det.sumTotal(det_psn);

            // Menampilkan total ke label
            lb_total.setText(det_psn.getSubtotal_pesan().toString());

            // Memuat ulang data sementara ke tabel
            loadDataSementara();

            // Memunculkan dialog konfirmasi
            SwingUtilities.invokeLater(() -> {
                int pilihan = JOptionPane.showConfirmDialog(this, "Mau Tambah Barang?",
                        "Konfirmasi", JOptionPane.YES_NO_OPTION);

                // Log untuk debugging
                System.out.println("Pilihan user: " + pilihan);

                if (pilihan == JOptionPane.YES_OPTION) {
                    bersihBarang();
                    aktifBarang();
                    btn_barang.requestFocus();
                } else {
                    bersihBarang();
                }
            });
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input tidak valid. Pastikan semua field diisi dengan benar!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_tambahSementaraActionPerformed

    private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
        Long harga, subtotal;
        int jumlah;

        harga = Long.parseLong(t_harga.getText());
        String inputJumlah = txt_jumlah.getText();
        if (inputJumlah.isEmpty()) {
            jumlah = 0;
        } else {
            jumlah = Integer.parseInt(inputJumlah);
        }

        subtotal = harga * jumlah;
        t_subtotal.setText(Long.toString(subtotal));
        t_subtotal.setEnabled(false);
    }//GEN-LAST:event_txt_jumlahKeyReleased

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        loadData();
        bersihBarang();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_perbarui4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perbarui4ActionPerformed
        perbaruiDataSementara();
    }//GEN-LAST:event_btn_perbarui4ActionPerformed

    private void tbl_sementaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sementaraMouseClicked
        int row = tbl_sementara.getSelectedRow();

        t_kodeBarang.setEnabled(false);
        t_namaBarang.setEnabled(false);
        t_satuan.setEnabled(false);
        t_harga.setEnabled(false);
        t_subtotal.setEnabled(false);

        t_kodeBarang.setText(tbl_sementara.getModel().getValueAt(row, 0).toString());
        t_namaBarang.setText(tbl_sementara.getModel().getValueAt(row, 1).toString());
        t_satuan.setText(tbl_sementara.getModel().getValueAt(row, 2).toString());
        t_harga.setText(tbl_sementara.getModel().getValueAt(row, 3).toString());
        txt_jumlah.setText(tbl_sementara.getModel().getValueAt(row, 4).toString());
        t_subtotal.setText(tbl_sementara.getModel().getValueAt(row, 5).toString());

        txt_jumlah.setEnabled(true);
        lb_satuan.setEnabled(false);
        t_satuan.setEnabled(false);

    }//GEN-LAST:event_tbl_sementaraMouseClicked

    private void btn_hapus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus4ActionPerformed
        hapusDataSementara();
    }//GEN-LAST:event_btn_hapus4ActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        String distributorName = t_namaDistributor.getText();

// Validasi distributorName sebelum mencetak
        if (distributorName == null || distributorName.trim().isEmpty()) {
            System.err.println("Nama distributor tidak boleh kosong.");
            return;
        }

        MessageFormat header = new MessageFormat("Pemesanan Barang Dari Toko Parfum Tuntungan dua");
        MessageFormat footer = new MessageFormat("Kepada: " + distributorName);

        try {
            tbl_sementara.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print: %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btn_cetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_barang;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JToggleButton btn_distributor;
    private javax.swing.JButton btn_hapus4;
    private javax.swing.JButton btn_perbarui4;
    private javax.swing.JButton btn_tambahSementara;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_satuan;
    private javax.swing.JLabel lb_total;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_harga;
    private javax.swing.JTextField t_idDistributor;
    private javax.swing.JTextField t_kodeBarang;
    private javax.swing.JTextField t_namaBarang;
    private javax.swing.JTextField t_namaDistributor;
    private javax.swing.JTextField t_satuan;
    private javax.swing.JTextField t_subtotal;
    private javax.swing.JPanel tambahData;
    private javax.swing.JTable tbl_sementara;
    private javax.swing.JTextField txt_jumlah;
    // End of variables declaration//GEN-END:variables

    private void loadDataSementara() {
        List<Model_SemPemesanan> list = servis_sem.getData();
        tblModel_sem.setData(list);

        Model_DetPemesanan det_psn = new Model_DetPemesanan();
        servis_det.sumTotal(det_psn);
        lb_total.setText(det_psn.getSubtotal_pesan().toString());

    }

    /* private void resetForm() {
    btn_tambah.requestFocus();
    btn_tambah.setText("TAMBAH");
    t_tglPesan.setText("");
    t_noPesan.setText("");
    txt_TotalPesan.setText("");
    cmb_Distributor.setSelectedIndex(0);
    cmb_Pengguna.setSelectedIndex(0);
}*/
    private void tampilPanel() {
        mainPanel.removeAll();
        //string Id = lb_id.getText();
        mainPanel.add(new Transaksi_Pemesanan());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void perbaruiDataSementara() {
        int index = tbl_sementara.getSelectedRow();
        if (index != -1) {
            Model_SemPemesanan model = tblModel_sem.getData(tbl_sementara.convertRowIndexToModel(index));

            String kode = t_kodeBarang.getText();
            String nama = t_namaBarang.getText();
            String satuan = t_satuan.getText();
            Long harga = Long.parseLong(t_harga.getText());
            Long jumlah = Long.parseLong(txt_jumlah.getText());
            long subtotal = Long.parseLong(t_subtotal.getText());

            Model_Barang brg = new Model_Barang();
            brg.setKode_barang(kode);
            brg.setNama_barang(nama);
            brg.setSatuan(satuan);
            brg.setHarga(harga);

            Model_DetPemesanan det = new Model_DetPemesanan();
            det.setSubtotal_pesan(subtotal);
            det.setJml_pesan(jumlah);

            Model_SemPemesanan sem = new Model_SemPemesanan();
            sem.setMod_barang(brg);
            sem.setMod_detpesan(det);

            servis_sem.perbaruiData(sem);

            tblModel_sem.perbaruiData(index, sem);
            servis_det.sumTotal(det);
            lb_total.setText(det.getSubtotal_pesan().toString());
            loadDataSementara();
            bersihBarang();

            aktifBarang();

        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan diperbaharui");
        }
    }

    private void dataTabel() {

        tambahData.setVisible(true);

        int row = tbl_sementara.getSelectedRow();

        // Set nilai dari tabel ke input form
        t_kodeBarang.setText(tbl_sementara.getModel().getValueAt(row, 0).toString());
        t_namaBarang.setText(tbl_sementara.getModel().getValueAt(row, 1).toString());
        t_satuan.setText(tbl_sementara.getModel().getValueAt(row, 2).toString());
        t_harga.setText(tbl_sementara.getModel().getValueAt(row, 3).toString());
        txt_jumlah.setText(tbl_sementara.getModel().getValueAt(row, 4).toString());
        t_subtotal.setText(tbl_sementara.getModel().getValueAt(row, 5).toString());

    }

    private void bersihBarang() {
        t_kodeBarang.setText("");
        t_namaBarang.setText("");
        t_satuan.setText("");
        t_harga.setText("");
        txt_jumlah.setText("");
        t_subtotal.setText("");

    }

    private void aktifBarang() {
        t_kodeBarang.setEnabled(true);
        t_namaBarang.setEnabled(true);
        t_satuan.setEnabled(true);
        t_harga.setEnabled(true);
        txt_jumlah.setEnabled(true);
        t_subtotal.setEnabled(true);
    }

    private void resetForm() {
    }

    private void hapusDataSementara() {
        int index = tbl_sementara.getSelectedRow(); // Mendapatkan indeks baris yang dipilih pada tabel
        if (index != -1) { // Memastikan ada baris yang dipilih
            Model_SemPemesanan data = tblModel_sem.getData(tbl_sementara.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                servis_sem.hapusData(data); // Memanggil fungsi hapusData pada DAO
                tblModel_sem.hapusData(index); // Menghapus data dari model tabel
                loadDataSementara();
                aktifBarang();
                bersihBarang();
            } else {
                JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan dihapus");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang dipilih untuk dihapus.");
        }
    }

    private void loadData() {
        btn_tambahSementara.setVisible(true);

    }

}
